// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace ProyectoFinal.Infraestructura.Datos.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class iojn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(iojn));
        
        string IMigrationMetadata.Id
        {
            get { return "201508061644138_iojn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
