// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace ProyectoFinal.Infraestructura.Datos.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Prueba : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Prueba));
        
        string IMigrationMetadata.Id
        {
            get { return "201508061555264_Prueba"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
